# Generated by Django 2.2 on 2019-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=50)),
                ('article_author', models.CharField(default='moo', max_length=20)),
                ('article_date', models.DateTimeField(verbose_name='date published')),
                ('article_text', models.CharField(max_length=10000)),
                ('article_views', models.IntegerField(default=0)),
            ],
        ),
    ]
