# Generated by Django 2.2 on 2019-09-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
